# exp
exp_name: "CNO_turek_hron_data_structure"
gpu: 0
seed: 0
results_path: "./results/"

# data
dataset_name: "turek_hron_data" # fluidzero_data, double_cylinder_simulation_data, double_cylinder_measurement_data
dataset_path: "/home/jblabro/Documents/GenCP_data/Datasets/"
num_workers: 4
normalizer: "range"
n_data_set: null  # 限制使用的数据量，null表示使用全部数据
length: 999 # 1000
dt: 5
sdf_threshold: 0.02

# choose
stage: "structure" # structure, fluid
model_name: "CNO" # SiT, UNet3d, CNO

use_torchcfm: True
use_diffusion: False 
use_surrogate: False

# model
is_resume: False
checkpoint_path: "/home/jblabro/Documents/GenCP/GenCP/results/turek_hron_data/structure_CNO/2026-09-09_09-57-12/best_main_model.pth"
input_size: [108, 88] # [322, 226]
in_dim: 4
out_dim: 1
in_channels: 4
out_channels: 1
in_size: 108
# hidden_size: 128 # 768
# patch_size: [2, 2]
# num_heads: 4 # 12 
depth: 2 # 12 
# use_wavelet: False

# training
is_use_tb: True
x0_is_use_noise: True
test_interval: 1000
train_batch_size: 8
test_batch_size: 8

input_step: 3
output_step: 12
stride: 1
num_delta_t: 0 # 20

lr: 0.0003
sigma: 0.01

# iteration
train_mode: "iteration" # epoch, iteration
total_iterations: 100000
epochs: 1000

scheduler: "cosine"
# cosine
T_max: 100000
#step
step_size: 50
gamma: 0.5

# inference
num_sampling_steps: 10

# visualize
save_figs_path: "./visualization_results"


channel_multiplier: 16